### ISSUE TITLE
WSH error message on run

### ISSUE THREAD

**Issue by Tridens92** [shaderzz/gpxmaker#1]
Hi, when I run the .js file I get the following error in Windows Script Host:

Script: D:\[path where i've unzipped your program\gpxmaker.js
Line: 2
Char: 1
Error: Syntax error
Code: 800A03EA
Source: Microsoft Jscript compilation error

Thanks for any help you can provide.

**Comment by shaderzz** [comment]
Hi. You need to run index.html instead.
