### ISSUE TITLE
GPX files are empty / contain no data

### ISSUE THREAD

**Issue by joranv1** [shaderzz/gpxmaker#2]
So I've tried multiple .json files but when I import them in Strava, I get the following error: "The file is empty". Can you help me? I attached the 2 JSON files (it was just a test "run" of 30 seconds) and the gpx file it made.
EDIT: seems like I can't attach those files so here you can download them: https://drive.google.com/drive/folders/1e70ma7GmDLo_uWX5DnPy_irbT3uMREnS?usp=sharing

I also tried longer runs that are like an hour-long but those also give me the same error.

**Comment by shaderzz** [comment]
Hi,
there is no any location data in your files. Perhaps you are using a training mode that does not recording information about your location (for example Treadmill or another internal workout modes), or in the selected mode geolocation recording is turned off. Or you are using the wrong files. In my case filename was xxxxx-xxx.location_data.json, not xxxxx-xxx.location_data_internal.json

**Comment by joranv1** [comment]
When using a location_data.json file, it worked creating a gpx file that isn't empty. Now I have another problem. All my activities use GPS (all my activities are run activities) but some of them don't have an location_data.json file and a lot of these json files are just empty, they only have "[]" in it. Is this normal? I just did a test activity of about 2 minutes outside with GPS but the location_data files are just empty or non-existent while the live_data file is also either empty or normal (with the correct data).

**Comment by EddyBin** [comment]
I manage to make a nice GPX file with my bike trip however the purpose is to add the heart_rate data
![image](https://user-images.githubusercontent.com/23278795/170125281-b8068082-92ae-426b-b695-147a5ff54684.png)

However the heart_rate data is not pick-up. I tried to debug the javascript but is appears that only a few distance point are collecta in "data"

[json files samsung health](https://drive.google.com/drive/folders/1PDvjnpyde9bmuaXBSEGS5tvcHY_hmkyl?usp=sharing)

What do I do wrong ?

**Comment by shaderzz** [comment]
Hi, @EddyBin 
I will check and let you know as soon as I have a solution for your case. Thank you

**Comment by EddyBin** [comment]
As far as I know the issue I reported still exist.

**Comment by joranv1** [comment]
I advise you to create a new issue since it's different from my issue.
